apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg-clusters
  namespace: argocd
spec:
  project: default
  source:
    path: pg-cluster
    repoURL: 'https://github.com/luizzvinicius/gitops-cnpg.git'
    targetRevision: HEAD
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
